In [7]:
import numpy as np

In [16]:
#python is a dynamically typed language
#python is slower compartive to c but it is more flexible
#numpy is a python library but behind the scene it make use of c language
#It make the process faster when dealing with huge volume of data
arr1 = np.array([1,2,3])
print(arr1)
print(arr1 * 2)

[1 2 3]
[2 4 6]


In [17]:
type(arr1)

numpy.ndarray

In [18]:
#dimention of the arr
arr1.shape

(3,)

In [20]:
#similar to range method in python
arr2 = np.arange(1,5)
arr2

array([1, 2, 3, 4])

In [21]:
arr3 = np.arange(1,5,0.5)#step size
arr3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [23]:
# The type changes because of one element 
arr4 = np.array([1,2,3,4.0])
arr4

array([1., 2., 3., 4.])

In [24]:
arr5 = np.array([1,2,3,4], dtype='float')
arr5

array([1., 2., 3., 4.])

In [29]:
arr6 = np.array([0,10,100])
arr6 ** 100

array([0, 0, 0], dtype=int32)

In [33]:
#Two dimentional array

m1 = np.array([[1,2],[3,4]])
m1 * 2

array([[2, 4],
       [6, 8]])

In [37]:
m1 = np.arange(1,13)
m1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
m2 = np.arange(9)
m3= m2.reshape(3,3)

In [43]:
m2.shape
m3.shape

(3, 3)

In [47]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
np.arange(9).reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [50]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
 np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [54]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
m1 = np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
m1[1,3]

np.int32(7)

In [64]:
m1[0,1:3]

array([1, 2])

In [71]:
m1[0:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [73]:
m1[0: , 1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [74]:
m1[:,(1,3)]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [78]:
m1 = np.arange(12).reshape(3,4)
m1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [79]:
m1[m1<6]

array([0, 1, 2, 3, 4, 5])

In [82]:
m1[m1%2==0].reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [84]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a+b

array([3, 5, 7])

In [85]:
a * b

array([ 2,  6, 12])

In [90]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
B = np.arange(12).reshape(4,3)
B

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [97]:
np.matmul(A,B)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [98]:
A @ B

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [99]:
B @ A

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [100]:
np.dot(A,B)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [101]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [109]:
np.dot(a,A)

array([32, 38, 44, 50])

In [110]:
np.matmul(a,A)

array([32, 38, 44, 50])

In [111]:
a @ A

array([32, 38, 44, 50])

In [112]:
a = np.arange(3)
a.T

array([0, 1, 2])

In [115]:
a = np.arange(3).reshape(1,3)
print(a)
a.T

[[0 1 2]]


array([[0],
       [1],
       [2]])

In [117]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
A.reshape(12,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [124]:
A.shape

(3, 4)

In [125]:
A.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [126]:
A.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [127]:
B = np.arange(24).reshape(2,3,4)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [128]:
B[0,0,0]

np.int32(0)

In [129]:
B[1,1,1]

np.int32(17)

In [135]:
 A = np.arange(12).reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [131]:
B = np.arange(3).reshape(1,3)
B

array([[0, 1, 2]])

In [132]:
print(A.shape, B.shape)

(3, 4) (1, 3)


In [136]:
A + B

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [138]:
np.random.randint(1,10,50)

array([6, 3, 5, 5, 7, 3, 7, 5, 3, 8, 8, 1, 8, 1, 8, 2, 1, 5, 7, 6, 3, 5,
       3, 9, 1, 8, 6, 3, 4, 9, 9, 9, 8, 8, 6, 7, 9, 6, 4, 4, 1, 9, 1, 1,
       9, 4, 9, 5, 9, 2])

In [139]:
np.random.rand(100)

array([0.11257084, 0.69846015, 0.30934157, 0.12895401, 0.06976992,
       0.43346625, 0.2449557 , 0.44361363, 0.32549802, 0.26359976,
       0.67989046, 0.60117118, 0.5794835 , 0.4880172 , 0.18205405,
       0.39080243, 0.28558601, 0.53919784, 0.23368529, 0.56200987,
       0.47065998, 0.2609477 , 0.02373787, 0.77258198, 0.26056069,
       0.63100941, 0.19605066, 0.04074132, 0.69760788, 0.93513809,
       0.14573276, 0.67300338, 0.03875091, 0.84508558, 0.74633991,
       0.86354545, 0.47172711, 0.71110465, 0.03921744, 0.08051063,
       0.4675484 , 0.38516007, 0.98735724, 0.15486345, 0.1830957 ,
       0.30149676, 0.10874108, 0.80404835, 0.96134492, 0.10691433,
       0.88188706, 0.25144239, 0.34632601, 0.89479131, 0.13249076,
       0.89563812, 0.30130412, 0.10214285, 0.7136689 , 0.41243153,
       0.76020186, 0.16141792, 0.10259448, 0.29664332, 0.5591041 ,
       0.1135993 , 0.09153797, 0.91001173, 0.93771443, 0.69539182,
       0.3486481 , 0.86336247, 0.02047237, 0.06215262, 0.33349

In [143]:
50+ np.random.rand(3)*25

array([67.54083515, 71.95718083, 67.41873073])